basePath: /
definitions:
  entity.User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: ユーザー管理サーバーの起動
  title: ユーザー管理API
  version: "1.0"
paths:
  /auth/users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ユーザー一覧
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
      summary: ユーザー一覧を取得
      tags:
      - user
  /auth/users/:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: 編集成功
          schema:
            $ref: '#/definitions/entity.User'
      summary: 新規ユーザーを作成
      tags:
      - user
  /auth/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 削除成功
          schema:
            $ref: '#/definitions/entity.User'
      summary: ユーザー情報を削除
      tags:
      - user
    get:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "201":
          description: 作成されたユーザー情報
          schema:
            $ref: '#/definitions/entity.User'
      summary: ユーザーを取得
      tags:
      - user
    put:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 削除されたユーザーID
          schema:
            type: integer
      summary: ユーザー情報を編集
      tags:
      - user
  /auth/validate:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer トークン
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 認証済みユーザー情報
          schema:
            $ref: '#/definitions/entity.User'
      summary: トークン検証
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: ログイン情報（IDとパスワード）
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: アクセストークン
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ログイン
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: 作成されたユーザー情報
          schema:
            $ref: '#/definitions/entity.User'
      summary: ユーザー登録
      tags:
      - auth
swagger: "2.0"
