basePath: /
definitions:
  system.Response:
    properties:
      message:
        description: メッセージ（詳細説明）
        type: string
      status:
        description: ステータス（成功、失敗など）
        type: string
    type: object
  user.RequestUserParam:
    properties:
      email:
        description: メールアドレス（必須）
        type: string
      name:
        description: ユーザー名（必須）
        type: string
    required:
    - email
    - name
    type: object
  user.Response:
    properties:
      message:
        description: メッセージ（詳細説明）
        type: string
      status:
        description: ステータス（成功、失敗など）
        type: string
    type: object
  user.ResponseUser:
    properties:
      email:
        description: メールアドレス
        type: string
      id:
        description: ユーザーID
        type: string
      name:
        description: ユーザー名
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: ユーザー管理サーバーの起動
  title: ユーザー管理API
  version: "1.0"
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 成功時のレスポンス
          schema:
            $ref: '#/definitions/system.Response'
      summary: 死活監視用
      tags:
      - healthcheck
  /v1/users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ユーザー一覧
          schema:
            items:
              $ref: '#/definitions/user.ResponseUser'
            type: array
      summary: ユーザー一覧を取得
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RequestUserParam'
      produces:
      - application/json
      responses:
        "200":
          description: 編集成功
          schema:
            $ref: '#/definitions/user.Response'
      summary: ユーザー情報を編集
      tags:
      - user
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 削除成功
          schema:
            $ref: '#/definitions/user.Response'
      summary: ユーザー情報を削除
      tags:
      - user
    get:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ユーザー詳細
          schema:
            $ref: '#/definitions/user.ResponseUser'
      summary: ユーザーの詳細情報を取得
      tags:
      - user
swagger: "2.0"
